language: python
python:
    - 3.5

install:
    - pip install -r requirements.txt
    - pip install flake8 coverage

script:
    - flake8 .
    - coverage run -m unittest discover
    - coverage report -m

notifications:
  email:
    recipients:
        - agilis@sch.bme.hu
    on_success: change
    on_failure: always
